# Generated by Django 5.2.3 on 2025-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_cell_analysis_count_cell_has_analysis_cellanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='pixels_per_micron',
            field=models.FloatField(blank=True, help_text='Pixels per micron for scale calibration', null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scale_reference_length_microns',
            field=models.FloatField(blank=True, help_text='Known real-world length in microns', null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scale_reference_length_pixels',
            field=models.FloatField(blank=True, help_text='Reference length in pixels for calibration', null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scale_set',
            field=models.BooleanField(default=False, help_text='Whether scale calibration has been set'),
        ),
    ]
