# Generated by Django 5.2.3 on 2025-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_cell_pixels_per_micron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcell',
            name='area_microns_sq',
            field=models.FloatField(blank=True, help_text='Area in μm²', null=True),
        ),
        migrations.AddField(
            model_name='detectedcell',
            name='major_axis_length_microns',
            field=models.FloatField(blank=True, help_text='Major axis length in μm', null=True),
        ),
        migrations.AddField(
            model_name='detectedcell',
            name='minor_axis_length_microns',
            field=models.FloatField(blank=True, help_text='Minor axis length in μm', null=True),
        ),
        migrations.AddField(
            model_name='detectedcell',
            name='perimeter_microns',
            field=models.FloatField(blank=True, help_text='Perimeter in μm', null=True),
        ),
    ]
