# Generated by Django 5.2.3 on 2025-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_detectedcell_area_microns_sq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellanalysis',
            name='roi_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ROI regions selected'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='roi_regions',
            field=models.JSONField(blank=True, default=list, help_text='ROI regions as list of rectangles [x, y, width, height]'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='use_roi',
            field=models.BooleanField(default=False, help_text='Whether to use ROI selection'),
        ),
    ]
