# Generated by Django 5.2.3 on 2025-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0005_cellanalysis_roi_count_cellanalysis_roi_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellanalysis',
            name='apply_preprocessing',
            field=models.BooleanField(default=False, help_text='Whether to apply image preprocessing'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='preprocessing_applied',
            field=models.BooleanField(default=False, help_text='Whether preprocessing was actually applied'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='preprocessing_options',
            field=models.JSONField(blank=True, default=dict, help_text='Preprocessing configuration options'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='preprocessing_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of preprocessing steps that were applied'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='quality_category',
            field=models.CharField(blank=True, help_text='Quality category: excellent, good, fair, poor', max_length=20),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='quality_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Image quality assessment metrics'),
        ),
        migrations.AddField(
            model_name='cellanalysis',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Overall image quality score (0-100)', null=True),
        ),
    ]
